name: Check and/or update UI5 version for CF
description: Checks and/or updates the UI5 versions used in SAP Build Workzone
author: DevEpos

branding:
  icon: shield
  color: blue

inputs:
  manifestPaths:
    description: >
      A comma or newline-separated list of file paths that point to a folder containing a `manifest.json` file of a UI5
      application. The paths can also be specified using glob patterns like app/**/webapp
  allowedDaysBeforeEocp:
    description: >
      Number of allowed days before the end of the eocp quarter (e.g. Q1/2024)
    default: "30"
  fixOutdated:
    description: >
      Automatically updates the used UI5 version to either the latest or lts UI5 version available
    default: "false"
  useLTS:
    description: >
      If `true` the latest available LTS version will be used to update the manifest.json files, otherwise the newest
      maintained version will be used.  
      Only relevant if `fixOutdated` is set to true.
    default: "false"
  eomAllowed:
    description: >
      If `true`, versions that reached only the status "End of Maintenance" will produce warnings only and not result in
      an action failure
    default: "true"
outputs:
  foundManifests:
    description: Paths to all found manifest.json files
  modifiedFiles:
    description: List of newline-separated file paths of manifest.json files that have been updated
  summary:
    description: Summary of all checked manifest files (as HTML string)

runs:
  using: node20
  main: dist/index.js
