name: Check and/or update UI5 version for CF
description: Checks and/or updates the UI5 versions used in SAP Build Workzone
author: DevEpos

branding:
  icon: shield
  color: blue

inputs:
  manifestPaths:
    description: >
      A comma or newline-separated list of file paths that point to a folder containing a `manifes.json` file of a UI5
      application. The paths can also be specified using glob patterns like app/**/webapp
  fixOutdated:
    description: >
      Automatically updates the used UI5 version to either the latest or lts UI5 version available
    default: "false"
  useLatest:
    description: >
      If true, the latest available version will be use used to update the manifest.json files.  
      Only relevant if `fixOutdated` is set to true.
    default: "false"
  useLatestLts:
    description: >
      If `true` the latest available LTS version will be used to update the manifest.json files.  
      Only relevant if `fixOutdated` is set to true.
    default: "false"
outputs:
  modifiedManifests:
    description: List of comma-separated file paths of manifest.json files that have been updated

runs:
  using: node20
  main: dist/index.js
